name: play
description: "Firebase basic connection app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: 1.0.3
  firebase_core: any
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  fluttertoast: ^8.2.5
  google_sign_in: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: mafia
      fonts:
        - asset: Fonts/mafia.ttf
    - family: game
      fonts:
        - asset: Fonts/game.ttf
